name: Check

on:
  pull_request:
    branches: [ main ]

env:
  NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    timeout-minutes: 20

    permissions:
      packages: read
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache turbo
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Cache Docker
        uses: ScribeMD/docker-cache@0.5.0
        with:
          key: docker-${{ runner.os }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.4.x

      - name: Install dependencies
        run: npm ci

      - name: Linter check for package
        run: npm run pack:lint

      - name: TypeScript check
        run: npm run dev:check

      - name: ESLint check
        run: npm run dev:lint

      - name: Run unit tests
        run: npm run test:unit

      - name: Run e2e tests
        run: npm run test:e2e
