name: Release
on:
  push:
    branches: [ main ]

env:
  HUSKY: 0
  IMAGE_REGISTRY: ghcr.io
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      packages: write
      contents: read

    strategy:
      matrix:
        service: [
          'backend',
          'frontend',
        ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Detect changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            source:
              - "services/${{ matrix.service }}/**"

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ env.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        if: steps.changes.outputs.source == 'true'
        with:
          push: true
          file: services/${{ matrix.service }}/dockerfile
          context: .
          platforms: linux/amd64
          tags: |
            ${{ env.IMAGE_REGISTRY }}/${{ github.repository }}/${{ matrix.service }}:${{ github.sha }}
            ${{ env.IMAGE_REGISTRY }}/${{ github.repository }}/${{ matrix.service }}:latest
          build-args: |
            APP_VERSION=${{ github.sha }}
